### ISSUE TITLE
Problem with phantomjs auto installer

### ISSUE THREAD

**Issue by sirlisko** [cedmax/qunit-amd-runner#2]
npm throws an error during phantom installation:

`✖ SyntaxError: Unexpected token
�TMs�0�+�Fq�8I{�0=���:����ƒǒۦ������2��a88���~�]i�8�Rr�����U�YrO}����B.�
��]��   ��Z�ƺZ�T
                ����lxt&o3�'}o���'�Be�{f�9CN�'�3�L��@n�ź�z��"9d2���Yl�-$~�P#�,F���crp!�i�N��>���
_G1'�u6�z��!6��O#�>(��g)�u�(�ڳ��R��^ڧ 1*���;�Un}-�GHfk5��%���i�#e�ߘJ��UV�jc��<[n�,[�mLV��2]�&�s�C=J6�ρ���Lb7��N���qc9�����A�  �
C���VzM�.V����uUZU�*�:�6U�,�Q,�M�{6����O��O6���O��ʜ���O�K,7���o£B�^"���d�B򸬻6c}O�}m.�W�?>�t�g
                                                                                             ��|C����U_�-�q>z����I�z�������g��l�_��i�V
R� �~��W ps`:�Bb�&�?o4F_��#J"'z�T�LX��
    at Object.parse (native)
    at RegClient.<anonymous> (node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:23)
    at Request.self.callback (node_modules/npm/node_modules/request/request.js:123:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (node_modules/npm/node_modules/request/request.js:893:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (node_modules/npm/node_modules/request/request.js:844:12)
    at emitNone (events.js:72:20)
/Users/lucalischetti/projects/archive/qunit-amd-runner/node_modules/parent-require/index.js:8
  throw new Error("Cannot find module '" + id + "' from parent")`

**Comment by sirlisko** [comment]
I think is related to https://github.com/npm/npm/issues/12196.

**Comment by sirlisko** [comment]
Problem solved. It was an issue with the npm registry (see above link for more info),
